import { YatraCampaign } from './types';

export const yatraCampaign: YatraCampaign = {
  headline: '6,000 kilometres. Twenty days. Driven entirely by persons with disability.',
  distance: '6,000 km',
  duration: '20 Days',
  driverCount: 5,
  storyParagraphs: [
    'Sangati Foundation announced a cross-country ride beginning 15 December 2024, from Delhi to the Sri Lanka border at Dhanushkodi, Rameshwaram. Founder Sudhir Dhir led a team of five people with disability driving modified vehicles.',
    'The flag-off was on Saturday 14 December from Modern School, Barakhamba Road, New Delhi, by Padma Shri Dr Deepa Malik. She charged up everyone — her presence alone was all the inspiration we could have wished for.',
    'The Yatra reached Hyderabad on 29 December, hosted by the Ideabytes team. It had been full of challenges and difficulties, and the team overcame them with grit and a practical, solution-finding approach.',
    'They did it. The longest ride ever undertaken by Divyang themselves to highlight both the problems and the solutions concluded on 3 January 2025, in a cold, foggy Delhi winter. There are no accolades enough to express even a fraction of what they achieved.',
  ],
  flagOffDetails: {
    date: '14 December 2024',
    location: 'Modern School, Barakhamba Road, New Delhi',
    flaggedOffBy: 'Padma Shri Dr Deepa Malik',
  },
  conclusionDetails: {
    date: '3 January 2025',
    location: 'New Delhi',
  },
  heroImage: '/images/hero/hero-yatra.jpg',
  bodyImage: '/images/featured/featured-02.jpg',
  stops: [
    {
      id: 'stop-1',
      name: 'New Delhi',
      state: 'Delhi NCR',
      distanceKm: 0,
      date: '14-15 Dec 2024',
      description: 'Grand Flag-off at Modern School, Barakhamba Road by Padma Shri Dr Deepa Malik.',
      isKeyStop: true,
    },
    {
      id: 'stop-2',
      name: 'Gwalior',
      state: 'Madhya Pradesh',
      distanceKm: 350,
      date: '17 Dec 2024',
      description: 'Accessibility check of highway rest stops and local historic monuments.',
      isKeyStop: false,
    },
    {
      id: 'stop-3',
      name: 'Nagpur',
      state: 'Maharashtra',
      distanceKm: 1050,
      date: '21 Dec 2024',
      description: 'Central India rally and interaction with regional disability advocacy groups.',
      isKeyStop: false,
    },
    {
      id: 'stop-4',
      name: 'Hyderabad',
      state: 'Telangana',
      distanceKm: 1550,
      date: '29 Dec 2024',
      description: 'Warm reception and hosting by the Ideabytes team; solution workshops on adaptive tech.',
      isKeyStop: true,
    },
    {
      id: 'stop-5',
      name: 'Bengaluru',
      state: 'Karnataka',
      distanceKm: 2120,
      date: '31 Dec 2024',
      description: 'Tech innovation forum on accessible software and adaptive mobility devices.',
      isKeyStop: false,
    },
    {
      id: 'stop-6',
      name: 'Rameshwaram & Dhanushkodi',
      state: 'Tamil Nadu',
      distanceKm: 3000,
      date: '1-2 Jan 2025',
      description: 'Reached the southern tip at Sri Lanka border point — proving distance is no barrier.',
      isKeyStop: true,
    },
    {
      id: 'stop-7',
      name: 'Return Leg (Northbound)',
      state: 'Across Central India',
      distanceKm: 4500,
      date: '2-3 Jan 2025',
      description: 'Relay driving through highway stretches, gathering road accessibility audit data.',
      isKeyStop: false,
    },
    {
      id: 'stop-8',
      name: 'New Delhi (Homecoming)',
      state: 'Delhi NCR',
      distanceKm: 6000,
      date: '3 Jan 2025',
      description: 'Triumphant return to a foggy Delhi winter, completing 6,000 km historic expedition.',
      isKeyStop: true,
    },
  ],
};
